### ISSUE TITLE
htf_vector keep calling realloc

### ISSUE THREAD

**Issue by trahay** [trahay/Hierarchical-Trace-Format#3]
When using a htf_vector to store timestamps, the vector will call realloc a lot of time which is time consuming.
To make timestamp storage more efficient, we should either:
- implement vectors as linked lists of array -> when an array is full, we can allocate a new one without having to copy GBs of data
- store timestamps with a double buffer: when a buffer is full, write it to disk (asynchronously) and use the other buffer for storing future timestamps

**Comment by khatharsis42** [comment]
I have implemented a linked list of array for now.
