### ISSUE TITLE
SIGSEGV when running mpi_ping

### ISSUE THREAD

**Issue by trahay** [trahay/Hierarchical-Trace-Format#4]
When running htf with eztrace  on a ping pong program, recording events with htf make the program crash.

Step to reproduce:
```
wget https://gitlab.com/eztrace/eztrace/-/blob/master/test/mpi/mpi_ping.c
mpicc -o mpi_ping.c -o mpi_ping
mpirun -np 2 eztrace -t mpi  ./mpi_ping
```

When changing the number of warmup loop to 0, the recording of events works fine. The problem may be due to a sequence appearing in several different loops.

**Comment by khatharsis42** [comment]
Corrected in 50e2dd7cc79acbc96e8583a3f0155b7c5b1c2d84
